-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.advertisers
(
    indexed boolean NOT NULL,
    paid boolean NOT NULL,
    verified boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone,
                                id uuid NOT NULL,
                                user_id uuid NOT NULL,
                                avatar_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    banner_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    public_location character varying(255) COLLATE pg_catalog."default" NOT NULL,
    public_url_location character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT advertisers_pkey PRIMARY KEY (id),
    CONSTRAINT advertisers_user_id_key UNIQUE (user_id)
    );

CREATE TABLE IF NOT EXISTS public.permissions
(
    created_at timestamp(6) with time zone NOT NULL,
                                updated_at timestamp(6) with time zone,
                                id uuid NOT NULL,
                                created_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_name_key UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS public.profiles
(
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone,
                                id uuid NOT NULL,
                                user_id uuid NOT NULL,
                                address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    avatar_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_user_id_key UNIQUE (user_id)
    );

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    revoked boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
                                expires_at timestamp(6) with time zone NOT NULL,
                                last_used_at timestamp(6) with time zone,
                                revoked_at timestamp(6) with time zone,
                                updated_at timestamp(6) with time zone,
                                family_id uuid NOT NULL,
                                id uuid NOT NULL,
                                replaced_by uuid,
                                token_jti uuid,
                                user_id uuid NOT NULL,
                                client_id character varying(255) COLLATE pg_catalog."default",
    created_by character varying(255) COLLATE pg_catalog."default",
    ip_address character varying(255) COLLATE pg_catalog."default",
    revoke_reason character varying(255) COLLATE pg_catalog."default",
    token_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    user_agent character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_replaced_by_key UNIQUE (replaced_by),
    CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash)
    );

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    created_at timestamp(6) with time zone NOT NULL,
                                id uuid NOT NULL,
                                permission_id uuid NOT NULL,
                                role_id uuid NOT NULL,
                                CONSTRAINT role_permissions_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.roles
(
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone,
                                id uuid NOT NULL,
                                created_by character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_description_key UNIQUE (description),
    CONSTRAINT roles_name_key UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS public.sessions
(
    revoked boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
                                last_seen_at timestamp(6) with time zone,
                                revoked_at timestamp(6) with time zone,
                                updated_at timestamp(6) with time zone,
                                family_id uuid NOT NULL,
                                id uuid NOT NULL,
                                user_id uuid NOT NULL,
                                client_id character varying(255) COLLATE pg_catalog."default",
    created_by character varying(255) COLLATE pg_catalog."default",
    ip_address character varying(255) COLLATE pg_catalog."default",
    revoke_reason character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    user_agent character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sessions_pkey PRIMARY KEY (id),
    CONSTRAINT sessions_family_id_key UNIQUE (family_id)
    );

CREATE TABLE IF NOT EXISTS public.user_roles
(
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    role_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.users
(
    account_non_expired boolean NOT NULL,
    account_non_locked boolean NOT NULL,
    credential_non_expired boolean NOT NULL,
    email_verified boolean NOT NULL,
    enable boolean NOT NULL,
    google_connected boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    tokens_invalid_before timestamp(6) with time zone,
                                updated_at timestamp(6) with time zone,
                                id uuid NOT NULL,
                                created_by character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
    );

ALTER TABLE IF EXISTS public.advertisers
    ADD CONSTRAINT fk99a8ajxxms2g3q0hfjcpxgjdw FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS advertisers_user_id_key
    ON public.advertisers(user_id);


ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT fk410q61iev7klncmpqfuo85ivh FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS profiles_user_id_key
    ON public.profiles(user_id);


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT fk1rgnsj36schrq0ixqjbs05dxy FOREIGN KEY (replaced_by)
    REFERENCES public.refresh_tokens (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS refresh_tokens_replaced_by_key
    ON public.refresh_tokens(replaced_by);


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT fkruie73rneumyyd1bgo6qw8vjt FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;