# suppress inspection "SpellCheckingInspection" for whole file
# suppress inspection "UnusedProperty" for whole file
spring.application.name=demo
spring.profiles.active=dev

# ===============================
# PostgreSQL Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-alpaca
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.secret.key=classpath:pass/secret.key
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA and Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.org.springframework.data.jpa.domain.support=DEBUG

# ===============================
# Configuring Application Metrics
# ===============================
# management.endpoints.web.exposure.include=*
# management.endpoint.metrics.enabled=true
# management.metrics.export.prometheus.enabled=true

# ===============================
# JWT - Access Token (RSA-4096)
# ===============================
security.jwt.access.private-key-path=classpath:keys/access_private.pem
security.jwt.access.public-key-path=classpath:keys/access_public.pem
security.jwt.access.expiration=${JWT_ACCESS_TOKEN_EXPIRATION}

# ===============================
# JWT - Refresh Token (RSA-4096)
# ===============================
security.jwt.refresh.private-key-path=classpath:keys/refresh_private.pem
security.jwt.refresh.public-key-path=classpath:keys/refresh_public.pem
security.jwt.refresh.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# ===============================
# JWT - Common / Metadata
# ===============================
security.jwt.issuer=${JWT_ISSUER}

# ===============================
# Maximum Sessions Per User
# ===============================
security.max.session.per.user=${MAX_SESSIONS_PER_USER}

# ===============================
# OAuth2 / Frontend
# ===============================
app.oauth2.authorized-redirect-uri=http://localhost:4200/oauth2/redirect
app.frontend.uri=http://localhost:4200/login

# ===============================
# Google OAuth2 Configuration
# ===============================
spring.security.oauth2.client.registration.google.clientId=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.clientSecret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirectUri={baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email, profile