name: Workflow for SonarQube
on:
  push:
    branches: [main]
    paths:
      - 'auth-alpaca-api/**'
  pull_request:
    branches: [main]
    paths:
      - 'auth-alpaca-api/**'
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    defaults: 
      run: 
        working-directory: auth-alpaca-api
    
    env:
      MAVEN_OPTS: >-
        -Xmx3g
        -XX:+UseG1GC
      TESTCONTAINERS_RYUK_DISABLED: false

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      
      - name: Make scripts executable
        run: chmod +x ../generate_keys.sh

      - name: Run key generation script
        run: ../generate_keys.sh -L src/test/resources/keys

      - name: Cache SonarQube packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rogelioolarte_auth-alpaca
