name: Workflow for Codecov auth-alpaca
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Install dependencies
        run: mvn install -B -V
        working-directory: backend

      - name: Run tests and collect coverage
        run: mvn -B test
        working-directory: backend

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
        working-directory: backend
